[flake8]
max-line-length = 135
max-complexity = 10
count = true
statistics = true
exclude =
    .git,
    __pycache__,
    .venv,
    env,
    node_modules
ignore = E501,

format = ::error file=%(path)s,line=%(row)d,col=%(col)d::%(code)s %(text)s

[isort]
profile = black
