SAD_QUOTES = [
    "It's okay to feel overwhelmed - you're doing something extraordinary and it's natural to feel scared.",
    "You don't have to be a perfect pregnant woman. You just have to be you, and that's enough.",
    "Some days will be harder than others, but your baby needs you just as you are.",
    "Your emotions are valid. Pregnancy is beautiful and terrifying, and you're allowed to feel both.",
    "It's okay to cry, to worry, to feel unsure. You're human, and you're doing your best.",
    "Your body is changing, and it's okay to feel strange in your own skin sometimes.",
    "You're not alone in feeling scared about becoming a mother. Every good mama feels this way.",
    "It's okay to grieve the life you had before while being excited for what's coming.",
    "Your fears about pregnancy and motherhood show how much you already love your baby.",
    "Some days you might not feel connected to your baby, and that's completely normal.",
    "You don't have to love every moment of pregnancy to be a good mother.",
    "It's okay to feel lost sometimes. You're becoming someone entirely new.",
    "Your hormones are doing wild things, and your feelings are completely valid.",
    "You're allowed to have bad days, even during this 'magical' time.",
    "It's normal to worry about whether you'll be a good enough mother - you already are.",
    "Your body might not feel like yours right now, but it's doing incredible work.",
    "It's okay to miss feeling like yourself. You're still you, just growing.",
    "You don't have to glow every day. Sometimes you just have to survive, and that's enough.",
    "Your anxiety about the future shows how much you care about your baby's wellbeing.",
    "It's okay to feel sad about losing your independence while gaining something beautiful.",
    "You're allowed to feel overwhelmed by all the advice everyone gives you.",
    "It's normal to worry about childbirth. Your body was made for this, even if it's scary.",
    "You don't have to have it all figured out. No one does, especially first-time mamas.",
    "It's okay to feel like you're losing yourself while creating someone new.",
    "Your baby will love you even on your hardest, messiest, most emotional days.",
    "It's normal to feel guilty about not enjoying every pregnancy moment.",
    "You're allowed to be tired, cranky, and not always grateful for morning sickness.",
    "It's okay to worry about your relationship changing - good love adapts and grows.",
    "You don't have to be strong all the time. It's okay to need support.",
    "Your baby doesn't need a perfect mother, they need their mother - you.",
    "It's normal to feel overwhelmed by how much your life is about to change.",
    "You're allowed to feel sad about your changing body while knowing it's doing amazing work.",
    "It's okay to have moments where you wonder if you're ready for this.",
    "Your baby chose you for a reason, even when you can't see it yourself.",
    "It's normal to feel like you have no idea what you're doing - no one really does.",
    "You're allowed to feel conflicted about pregnancy - it's a huge life change.",
    "It's okay to need time to process becoming a mother while your body changes.",
    "Your baby will think you're perfect, stretch marks, mood swings and all.",
    "It's normal to feel like pregnancy is taking forever and flying by at the same time.",
    "You don't have to love your pregnant body to love your baby growing inside.",
    "It's okay to feel scared about labor - you're stronger than you know.",
    "Your baby doesn't need you to be perfect, they need you to be present.",
    "It's normal to worry about being a good enough mother - you wouldn't worry if you weren't.",
    "You're allowed to have moments of doubt - they don't make you less capable.",
    "It's okay to feel lonely sometimes, even when you're never truly alone anymore.",
    "Your baby is lucky to have a mother who cares enough to worry about them.",
    "It's normal to feel like your body isn't yours anymore - it's working for both of you now.",
    "You don't have to enjoy every pregnancy symptom to be grateful for your baby.",
    "It's okay to feel unprepared - no one is ever truly ready to become a parent.",
    "Your love for your baby doesn't have to be constant to be real and powerful."
]

HAPPY_QUOTES = [
    "You're growing a human being inside you - you're literally creating magic every single day.",
    "Your body is doing the most incredible thing it will ever do. You are a miracle worker.",
    "There's a little miracle growing inside you, and you're glowing with the beauty of creation.",
    "You're not just pregnant, you're blooming into the most radiant version of yourself.",
    "Every kick, every flutter is your baby saying 'I love you, Mama.'",
    "You carry the future in your belly and stardust in your soul.",
    "Your pregnancy glow isn't just a myth - it's the light of pure love shining through you.",
    "You're creating life, nurturing dreams, and becoming the superhero your baby needs.",
    "Your bump is beautiful, your heart is full, and your future is bright.",
    "You're not gaining weight, you're gaining a miracle.",
    "Every day your baby grows stronger because of your love and care.",
    "You're writing the most beautiful love story that will last a lifetime.",
    "Your body knows exactly what to do - trust in its incredible wisdom.",
    "You're growing tiny fingers, tiny toes, and a heart full of love.",
    "The most precious gift you'll ever receive is already on the way.",
    "You're creating your own little piece of heaven right inside you.",
    "Your baby chose you to be their mama - what an honor and blessing.",
    "You're not just expecting a baby, you're expecting a lifetime of joy.",
    "Every stretch mark tells the story of how much you love your baby.",
    "You're building a nursery in your heart and a home in your womb.",
    "Your baby's first home is made of love, warmth, and your beautiful heartbeat.",
    "You're growing a little person who will call you 'Mama' - how amazing is that?",
    "Your pregnancy is proof that miracles happen every single day.",
    "You're creating the most precious masterpiece the world has ever seen.",
    "Every day brings you closer to holding your greatest blessing.",
    "You're not just carrying a baby, you're carrying hopes, dreams, and endless love.",
    "Your baby is so lucky to have you as their first home and forever protector.",
    "You're growing a tiny human who will make the world a more beautiful place.",
    "Your maternal instincts are already perfect - trust yourself completely.",
    "You're creating a love story that begins before birth and lasts forever.",
    "Your baby bump is the most beautiful curve your body has ever made.",
    "You're nurturing the most important relationship of your lifetime.",
    "Every flutter is your baby dancing with joy because they have you.",
    "You're growing someone who will love you unconditionally forever.",
    "Your pregnancy journey is painting the most beautiful memories in your heart.",
    "You're creating a tiny person who will make your heart infinitely bigger.",
    "Your body is working magic 24/7 - you're absolutely incredible.",
    "You're not just pregnant, you're incubating pure love and endless possibilities.",
    "Your baby is already so loved and hasn't even arrived yet.",
    "You're growing your best friend, your greatest love, your precious miracle.",
    "Every day of pregnancy is a day closer to the most beautiful hello.",
    "You're creating someone who will make your life infinitely more meaningful.",
    "Your baby's heartbeat is the most beautiful music you'll ever hear.",
    "You're growing a little piece of your heart outside your body.",
    "Your pregnancy glow comes from the pure joy radiating from within.",
    "You're creating a bond that nothing in this world can ever break.",
    "Your baby chose the most perfect mama in the whole wide world.",
    "You're growing tiny miracles every single second of every day.",
    "Your love for your baby is already infinite and growing stronger daily.",
    "You're about to become someone's whole world - and they're already yours.",
]

STRESSED_QUOTES = [
    "Take it one day at a time, one kick at a time, one breath at a time.",
    "You don't have to have everything ready right now. Your baby just needs you.",
    "Your body knows how to grow this baby. Trust in its incredible wisdom.",
    "You can't control everything about pregnancy, but you can control how you care for yourself.",
    "It's okay to say no to things that stress you out. Your peace matters for you and baby.",
    "You don't have to read every pregnancy book or follow every piece of advice.",
    "Your baby doesn't need a perfect nursery, they need a loving, calm mama.",
    "Focus on today. Tomorrow's worries can wait until tomorrow.",
    "You don't have to have all the answers right now. Motherhood is learned, not born.",
    "Your stress doesn't make you a bad mother. It makes you a caring one.",
    "Breathe deeply. Your baby feels your calm energy more than your stress.",
    "You don't have to do pregnancy perfectly. There's no such thing as perfect.",
    "Take breaks from pregnancy information overload. Trust your instincts instead.",
    "Your baby needs a rested mama more than a stressed, prepared one.",
    "It's okay to prioritize your mental health during pregnancy. It matters deeply.",
    "You don't have to make every decision about your baby right now.",
    "Your worth as a mother isn't measured by how much you prepare or worry.",
    "Take time to rest. Your body is working overtime growing a human.",
    "You don't have to have the perfect birth plan. Flexibility is your friend.",
    "Focus on nourishing yourself and your baby, not on everyone else's expectations.",
    "Your anxiety shows how much you love your baby, but they need your peace more.",
    "You don't have to prove you're ready to be a mother to anyone, including yourself.",
    "Take pregnancy one appointment, one milestone, one moment at a time.",
    "Your baby will adapt to your life. You don't have to change everything perfectly.",
    "It's okay to ask for help. Pregnancy is not meant to be done alone.",
    "You don't have to compare your pregnancy journey to anyone else's.",
    "Focus on what you can control: eating well, resting, and loving your baby.",
    "Your baby doesn't need you to stress about their future. They need your present love.",
    "It's okay to feel unprepared. Every mother learns on the job.",
    "You don't have to make every decision about parenting before your baby arrives.",
    "Your baby chose you because you're exactly the mother they need.",
    "Take time to connect with your baby instead of worrying about everything else.",
    "You don't have to have a perfect pregnancy to have a healthy, happy baby.",
    "Focus on the miracle happening inside you, not on all the things that could go wrong.",
    "Your baby doesn't need a stress-free mother, they need an authentic one.",
    "It's okay to change your mind about birth plans, parenting choices, anything.",
    "You don't have to solve every potential future problem during pregnancy.",
    "Your baby is growing perfectly according to their own timeline, not your timeline.",
    "Take deep breaths. Your baby loves the gentle rhythm of your relaxed breathing.",
    "You don't have to be the perfect pregnant woman. Just be the real you.",
    "Focus on bonding with your baby rather than stressing about being ready.",
    "Your baby doesn't need you to have it all figured out before they arrive.",
    "It's okay to take pregnancy one trimester, one week, one day at a time.",
    "You were chosen to be this baby's mother. That's all the qualification you need.",
    "Your love for your baby is already perfect, even if everything else feels chaotic.",
    "Take time to marvel at what your body is accomplishing instead of stressing about it.",
    "You don't have to earn your title as 'mother.' You already have it.",
    "Focus on creating a peaceful environment in your heart for you and your baby.",
    "Your baby doesn't need a perfect life planned out, they need a loving mother.",
    "Trust that you and your baby will figure this beautiful journey out together.",
]

ANGRY_QUOTES = [
    "Your hormones are doing wild things right now. This anger will pass, mama.",
    "It's okay to feel frustrated with your changing body. These feelings are temporary.",
    "You're not a bad person for feeling angry during pregnancy. You're human.",
    "Take a deep breath. Your baby feels your energy, so send them calm instead of chaos.",
    "Your anger doesn't define you as a mother. How you handle it does.",
    "It's normal to feel irritated when everyone has opinions about your pregnancy.",
    "You don't have to smile and be grateful every moment. Real emotions are okay.",
    "Your patience might be thin, but your love for your baby is infinite.",
    "It's okay to feel angry about pregnancy symptoms. They're hard to deal with.",
    "You're allowed to be frustrated when people touch your belly without asking.",
    "Your anger at unsolicited advice shows you're already protective of your baby.",
    "It's normal to feel irritated when you can't do things you used to do easily.",
    "You don't have to be sweet and docile just because you're pregnant.",
    "Your frustration with your partner's lack of understanding is completely valid.",
    "It's okay to be angry that your body doesn't feel like your own anymore.",
    "You're allowed to feel mad when people make comments about your size or shape.",
    "Your irritability doesn't make you a bad mother-to-be. It makes you real.",
    "It's normal to feel angry when you're uncomfortable and can't get relief.",
    "You don't have to hide your frustration to be a 'good' pregnant woman.",
    "Your anger at losing independence shows how much you value your autonomy.",
    "It's okay to feel frustrated when pregnancy isn't the magical experience you expected.",
    "You're allowed to be angry about morning sickness, swollen feet, and sleeplessness.",
    "Your baby doesn't need a constantly happy mother, they need an honest one.",
    "It's normal to feel irritated when everyone treats you like you're fragile.",
    "You don't have to suppress your anger to protect your baby. Feel it and let it go.",
    "Your frustration with your changing emotions is part of the pregnancy journey.",
    "It's okay to be angry when people act like pregnancy is just about the baby.",
    "You're allowed to feel frustrated when your comfort and needs are overlooked.",
    "Your anger about losing your pre-pregnancy body is a normal part of grieving.",
    "It's normal to feel irritated when you can't eat, drink, or do what you want.",
    "You don't have to be grateful for every pregnancy discomfort to love your baby.",
    "Your anger at feeling out of control of your own body is completely understandable.",
    "It's okay to feel frustrated when people minimize your pregnancy struggles.",
    "You're allowed to be angry about the physical and emotional toll of pregnancy.",
    "Your irritation with constant advice and opinions shows you trust your own instincts.",
    "It's normal to feel angry when pregnancy affects your work, relationships, or plans.",
    "You don't have to smile through pregnancy pain and discomfort for anyone.",
    "Your frustration with your partner's inability to understand is valid.",
    "It's okay to be angry that society expects you to love every moment of pregnancy.",
    "You're allowed to feel irritated when your needs become secondary to the baby's.",
    "Your anger doesn't harm your baby unless you hold onto it. Feel it and release it.",
    "It's normal to feel frustrated with the constant physical and emotional changes.",
    "You don't have to be zen and peaceful just because you're growing a human.",
    "Your anger about pregnancy limitations shows you're grieving your old life, and that's okay.",
    "It's okay to feel frustrated when your body does things you can't control.",
    "You're allowed to be angry about the unfairness of bearing the physical burden alone.",
    "Your irritability is often your body's way of saying you need rest or support.",
    "It's normal to feel angry when pregnancy doesn't match your expectations or dreams.",
    "You don't have to transform into a saint just because you're carrying a baby.",
    "Your anger is valid, your feelings matter, and you're still going to be an amazing mother.",
]
