name: Run Pytest for MomCare

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      HOST: "0.0.0.0"
      PORT: "8000"
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      SEARCH_API_KEY: ${{ secrets.SEARCH_API_KEY }}
      SEARCH_API_CX: ${{ secrets.SEARCH_API_CX }}
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PIXEL_API_KEY: ${{ secrets.PIXEL_API_KEY }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python3 tester.py
